### ISSUE TITLE
Emptying Cache

### ISSUE THREAD

**Issue by ChrisChiera** [BenjaminAdams/wp-redis-cache#32]
This looks great, and impressive numbers versus W3 Total Cache. However, can this and Total Cache be used together for even more impressive speeds and more importantly being able to retain w3's emptying cache feature? That is, everytime a post is changed by a client or another setting the appropriate cache is emptied on the front end.

If not using w3 total cache, and just wp-redis-cache, what is the process for having wordpress automatically empty the appropriate redis cache when posts and other items are changed in the admin by clients?

**Comment by BenjaminAdams** [comment]
I do not recommend using this plugin with any other caching plugin.

I built a wordpress plugin that will clear the cache if you update a post https://github.com/BenjaminAdams/wp-redis-cache/tree/master/wp-redis-cache

This plugin you can also change the default cache time of a post, it defaults to 12 hours.

~Ben

**Comment by ChrisChiera** [comment]
Great, thanks, I'll check it out!
