### ISSUE TITLE
Exclude pages

### ISSUE THREAD

**Issue by robbens** [BenjaminAdams/wp-redis-cache#37]
How can I exclude pages from ever being cached? 
In this case Woocommerce cart & checkout pages.

EDIT: I believe I found where to add excludes. Line 138:

    // When a page displays after an "HTTP 404: Not Found" error occurs, do not cache
        // When the search was used, do not cache
        if ((!is_404()) and (!is_search()) and (!is_page('cart')) and (!is_page('checkout')) ) {
            if ($unlimited) {
                $redis->set($redis_key, $html_of_page);
            } else {
                $redis->setex($redis_key, $seconds_cache_redis, $html_of_page);
           }
        }

**Comment by BenjaminAdams** [comment]
That looks like it would work!  Goodluck =)
