### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by EugeneLiang** [BenjaminAdams/wp-redis-cache#39]
Hi there, 

I found the installation instructions a little buggy, so i need your help here.

I followed your instructions and am currently stuck on the step where I need to replace `index.php` found in WordPress root directory with the `index.php` file your plugin provided. 

The `index.php` file in your plugin has only these lines:
`<?php
require('index-wp-redis.php');` 

However, upon installing the plugin with the `index.php` provided by the plugin, my wordpress pages/posts/home page etc returns an empty page.

Than, i changed the `index.php` file in your plugin to:

```
<?php
require('index-wp-redis.php');

/**
 * Front to the WordPress application. This file doesn't do anything, but loads
 * wp-blog-header.php which does and tells WordPress to load the theme.
 *
 * @package WordPress
 */

/**
 * Tells WordPress to load the WordPress theme and output it.
 *
 * @var bool
 */
define('WP_USE_THEMES', true);

/** Loads the WordPress Environment and Template */
require( dirname( __FILE__ ) . '/wp-blog-header.php' );
```

And placed it in my WordPress root directory.

Now, my wordpress installation is working fine again.

However, I am not sure if the page/posts are generated from Redis, or is it from MySQL.

May i know if my installation steps are correct ?

Cheers!

**Comment by BenjaminAdams** [comment]
The wording in your issue makes me think that you have the "plugin" and the root index file confused.  The 2 fileshttps://github.com/BenjaminAdams/wp-redis-cache/blob/master/index-wp-redis.php and  https://github.com/BenjaminAdams/wp-redis-cache/blob/master/index.php belong in the root directory of your Wordpress installation.

**Comment by EugeneLiang** [comment]
Hi there, 

apologies, yes I have placed both https://github.com/BenjaminAdams/wp-redis-cache/blob/master/index-wp-redis.php and https://github.com/BenjaminAdams/wp-redis-cache/blob/master/index.php in the root of the WordPress directory.

**Comment by BenjaminAdams** [comment]
You should have custom errors on and it won't show the php white screen of
death!
