### ISSUE TITLE
Can it work with the Mobile/PC theme switcher plugins?

### ISSUE THREAD

**Issue by 399425353** [BenjaminAdams/wp-redis-cache#40]
Can it work with the Mobile/PC theme switcher plugins?

**Comment by BenjaminAdams** [comment]
I have no idea what those are

**Comment by 399425353** [comment]
There are a plugin that can control WordPress to show different themes to visitors, when visitors use mobile to explorer the website, it will show mobile theme, when visitors use PC, then show pc theme.
It seems your wp-redis-cache still can not work with it.
